# Packages for this machine. Install with:
#   brew bundle install --file=Brewfile
# auto_config.sh drives this file; edit it here, not in the script.

# --- Taps (third-party) ---
tap "hashicorp/tap"
tap "oven-sh/bun"
tap "theboredteam/boring-notch"

# --- Formulae (CLI tools) ---
brew "ansible"
brew "ansible-lint"
brew "aria2"
brew "bat"
brew "btop"
brew "cmake"
brew "croc"
brew "duf"
brew "fd"
brew "fzf"
brew "gh"
brew "gnupg"
brew "go"
brew "helm"
brew "inxi"
brew "k9s"
brew "kubernetes-cli"
brew "lazydocker"
brew "lazygit"
brew "lazyssh"
brew "lsd"
brew "mole"
brew "neovim"
brew "nvm"
brew "oci-cli"
brew "opencode"
brew "p7zip"
brew "ripgrep"
brew "ruff"
brew "rust"
brew "smartmontools"
brew "speedtest-go"
brew "spicetify-cli"
brew "starship"
brew "tlrc"
brew "tmux"
brew "ty"
brew "uv"
brew "watch"
brew "wget"
brew "yt-dlp"
brew "zoxide"
brew "hashicorp/tap/terraform"
brew "oven-sh/bun/bun"

# --- Casks (GUI apps) ---
cask "android-platform-tools"
cask "antigravity"
cask "blip"
cask "boring-notch"
cask "brave-browser"
cask "bruno"
cask "chatgpt"
cask "claude"
cask "cursor"
cask "dbeaver-community"
cask "dockdoor"
cask "ente-auth"
cask "free-download-manager"
cask "gamehub"
cask "google-chrome"
cask "hiddenbar"
cask "keka"
cask "linearmouse"
cask "lm-studio"
cask "microsoft-teams"
cask "obsidian"
cask "openchamber"
cask "orbstack"
cask "protonvpn"
cask "raycast"
cask "redis-insight"
cask "spotify"
cask "stats"
cask "tailscale-app"
cask "telegram"
cask "termius"
cask "tradingview"
cask "utm"
cask "vagrant"
cask "vesktop"
cask "vlc"
cask "warp"
cask "whatsapp"
cask "zed"
